"""
Swirl macOS Automation Adapter (AppleScript & System API Bridge)
Executes native macOS commands on behalf of Swirl Jac Walkers
"""

import subprocess
import os

def run_applescript(script: str) -> dict:
    """Executes AppleScript command string via osascript CLI"""
    try:
        process = subprocess.run(
            ["osascript", "-e", script],
            capture_output=True,
            text=True,
            check=True
        )
        return {"success": True, "output": process.stdout.strip(), "error": None}
    except subprocess.CalledProcessError as e:
        return {"success": False, "output": None, "error": e.stderr.strip()}

def execute_mac_action(app_name: str, action: str, params: dict) -> dict:
    """Dispatches macOS application actions based on block parameters"""
    app_lower = app_name.lower()
    
    # 1. Apple Notes
    if "note" in app_lower:
        title = params.get("title", "Swirl Workflow Note")
        content = params.get("content", "Generated by Swirl Jac Walker")
        folder = params.get("folder", "Notes")
        
        script = f'''
        tell application "Notes"
            tell account "On My Mac"
                if not (exists folder "{folder}") then
                    make new folder with properties {{name:"{folder}"}}
                end if
                make new note at folder "{folder}" with properties {{name:"{title}", body:"<h1>{title}</h1><p>{content}</p>"}}
            end tell
        end tell
        '''
        return run_applescript(script)
        
    # 2. macOS System Notification
    elif "system" in app_lower or "notification" in app_lower:
        message = params.get("text", "Swirl Workflow Task Completed")
        title = params.get("title", "Swirl macOS Agent")
        sound = params.get("sound", "Glass")
        
        script = f'display notification "{message}" with title "{title}" sound name "{sound}"'
        return run_applescript(script)
        
    # 3. Finder Operations
    elif "finder" in app_lower:
        target_dir = os.path.expanduser(params.get("targetDirectory", "~/Desktop"))
        if action == "organize_by_extension":
            # Native Python desktop organizer
            organized_count = 0
            for filename in os.listdir(target_dir):
                filepath = os.path.join(target_dir, filename)
                if os.path.isfile(filepath) and not filename.startswith('.'):
                    ext = filename.split('.')[-1].upper() if '.' in filename else 'MISC'
                    ext_folder = os.path.join(target_dir, f"{ext}_Files")
                    os.makedirs(ext_folder, exist_ok=True)
                    os.rename(filepath, os.path.join(ext_folder, filename))
                    organized_count += 1
            return {"success": True, "output": f"Organized {organized_count} files into extension folders on Desktop"}
            
    # 4. Terminal Command Execution
    elif "terminal" in app_lower or action == "exec_shell":
        command = params.get("command", "echo 'Swirl executed'")
        try:
            res = subprocess.run(command, shell=True, capture_output=True, text=True, check=True)
            return {"success": True, "output": res.stdout.strip(), "error": None}
        except subprocess.CalledProcessError as err:
            return {"success": False, "output": None, "error": err.stderr.strip()}
            
    return {"success": False, "error": f"Unknown macOS App or Action: {app_name} / {action}"}
