/**
 * Swirl Native Tauri Desktop Bridge Service
 * Exclusively uses Tauri Rust native commands for macOS desktop automation.
 */

import { invoke } from '@tauri-apps/api/core';
import { listen } from '@tauri-apps/api/event';

export const isTauriEnvironment = () =>
  typeof window !== 'undefined' &&
  Boolean(window.__TAURI_INTERNALS__ || window.__TAURI__);

export async function invokeBackend(command, args = {}) {
  if (!isTauriEnvironment()) {
    throw new Error('The Swirl backend is available when running the Tauri desktop app.');
  }
  return invoke(command, args);
}

export async function compileWorkflowPrompt(prompt, useLlm = true) {
  return invokeBackend('compile_prompt', { prompt, useLlm });
}

export async function executeWorkflow(workflow, context = {}, approvals = []) {
  return invokeBackend('execute_workflow', {
    request: { ...workflow, context, approvals }
  });
}

export async function generateJacSource(workflow) {
  return invokeBackend('generate_jac_source', { workflow });
}

export async function listBuiltinMcpServers() {
  return invokeBackend('list_builtin_mcp_servers');
}

export async function getBackendHealth() {
  return invokeBackend('backend_health');
}

export function listenToWorkflowEvents(handler) {
  if (!isTauriEnvironment()) return Promise.resolve(() => {});
  return listen('swirl-workflow-event', (event) => handler(event.payload));
}

export async function executeMacScriptViaTauri(appName, action, params) {
  try {
    const appLower = appName.toLowerCase();

    // 1. Native Apple Notes Action via Tauri Rust Command
    if (appLower.includes('note')) {
      const title = params.title || 'Swirl Workflow Note';
      const content = params.content || 'Generated by Swirl Jac Walker inside Tauri';
      const folder = params.folder || 'Notes';

      const script = `
        tell application "Notes"
            tell account "On My Mac"
                if not (exists folder "${folder}") then
                    make new folder with properties {name:"${folder}"}
                end if
                make new note at folder "${folder}" with properties {name:"${title}", body:"<h1>${title}</h1><p>${content}</p>"}
            end tell
        end tell
      `;

      return await invoke('execute_mac_applescript', { script });
    }

    // 2. Native macOS System Notification via Tauri Rust Command
    if (appLower.includes('system') || appLower.includes('notification')) {
      const message = params.text || 'Swirl Task Completed';
      const title = params.title || 'Swirl Desktop Agent';
      const sound = params.sound || 'Glass';

      const script = `display notification "${message}" with title "${title}" sound name "${sound}"`;
      return await invoke('execute_mac_applescript', { script });
    }

    // 3. Native Terminal Shell Execution via Tauri Rust Command
    if (appLower.includes('terminal') || action === 'exec_shell') {
      const command = params.command || 'echo "Swirl execution completed in Tauri"';
      return await invoke('execute_mac_shell', { command });
    }

    return { success: true, output: `Tauri Rust executed ${appName} action: ${action}` };

  } catch (err) {
    console.error('[Tauri Native Bridge] Error invoking Rust command:', err);
    return { success: false, error: err.toString() };
  }
}
