/**
 * Swirl Native Tauri Desktop Bridge Service
 * Exclusively uses Tauri Rust native commands for macOS desktop automation.
 */

import { invoke } from '@tauri-apps/api/core';

export const isTauriEnvironment = () => true;

export async function executeMacScriptViaTauri(appName, action, params) {
  try {
    const appLower = appName.toLowerCase();

    // 1. Native Apple Notes Action via Tauri Rust Command
    if (appLower.includes('note')) {
      const title = params.title || 'Swirl Workflow Note';
      const content = params.content || 'Generated by Swirl Jac Walker inside Tauri';
      const folder = params.folder || 'Notes';

      const script = `
        tell application "Notes"
            tell account "On My Mac"
                if not (exists folder "${folder}") then
                    make new folder with properties {name:"${folder}"}
                end if
                make new note at folder "${folder}" with properties {name:"${title}", body:"<h1>${title}</h1><p>${content}</p>"}
            end tell
        end tell
      `;

      return await invoke('execute_mac_applescript', { script });
    }

    // 2. Native macOS System Notification via Tauri Rust Command
    if (appLower.includes('system') || appLower.includes('notification')) {
      const message = params.text || 'Swirl Task Completed';
      const title = params.title || 'Swirl Desktop Agent';
      const sound = params.sound || 'Glass';

      const script = `display notification "${message}" with title "${title}" sound name "${sound}"`;
      return await invoke('execute_mac_applescript', { script });
    }

    // 3. Native Terminal Shell Execution via Tauri Rust Command
    if (appLower.includes('terminal') || action === 'exec_shell') {
      const command = params.command || 'echo "Swirl execution completed in Tauri"';
      return await invoke('execute_mac_shell', { command });
    }

    return { success: true, output: `Tauri Rust executed ${appName} action: ${action}` };

  } catch (err) {
    console.error('[Tauri Native Bridge] Error invoking Rust command:', err);
    return { success: false, error: err.toString() };
  }
}
